version: '3.8'

services:

  backend:
    build: ./backend
    environment:
      - DB_PASSWORD=XXX_POSTGRES_PASSWORD_XXX
      - DB_HOST=database
      - DB_NAME=ucode
      - DB_USER=postgres
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  database:
    build: ./database
    container_name: db_ucode
    volumes:
      - database_dumps:/var/lib/postgresql/dumps
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=XXX_POSTGRES_PASSWORD_XXX
      - POSTGRES_DB=ucode

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'

  reverse-proxy:
    image: caddy:2.5.2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_config:/config
volumes:
  caddy_config:
  database_dumps:
  database_data:
    driver: local
    driver_opts:
      type: none
      device: "$PWD/database/container-data"
      o: bind