version: '3.8'

services:

  backend:
    build: ./backend
    environment:
      - DB_PASSWORD=XXX_POSTGRES_PASSWORD_XXX
      - DB_HOST=database
      - DB_NAME=ucode
      - DB_USER=postgres
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  database:
    build: ./database
    container_name: db_ucode
    volumes:
      - database_dumps:/var/lib/postgresql/dumps
      - database_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=XXX_POSTGRES_PASSWORD_XXX
      - POSTGRES_DB=ucode
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'

  tileserv:
    image: pramsey/pg_tileserv:latest
    environment:
      - DATABASE_URL=postgresql://postgres:XXX_POSTGRES_PASSWORD_XXX@database/ucode 
    ports:
      - 7800:7800
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy

  reverse-proxy:
    image: caddy:2.5.2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_config:/config
volumes:
  caddy_config:
  database_dumps:
  database_data:
      driver: local
      driver_opts:
        type: none
        device: "$PWD/database/container-data"
        o: bind