help:
	@echo "For now you are on your own :("

init:
	python3 -m venv --prompt ucode .venv

install-dev:
	pip install -r requirements-dev.txt

test:
	 python3 -m pytest -ra

run:
	uvicorn main:app --reload